apiVersion: v1
kind: Secret
metadata:
  name: cred-secret
  namespace: {{.Release.Namespace}}
type: Opaque
data:
  accesskey: {{.Values.accesskey | b64enc | quote}}
  secretkey: {{.Values.secretkey | b64enc | quote}}
