apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{.Release.Name}}-ingress-cert
  namespace: istio-ingress
spec:
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  secretName: {{.Values.certificate.secretName}}
  commonName: {{.Values.host}}
  dnsNames:
    - {{.Values.host}}
  duration: 2160h # 90d
  renewBefore: 360h # 15d
