#cloud-config

resize_rootfs: false

preserve_hostname: false
hostname: ${hostname}

write_files:
  - path: /etc/growroot-disabled
    content: |
      # Any text
  - path: /etc/netplan/60-floating-ip.yaml
    content: |
      network:
        version: 2
        renderer: networkd
        ethernets:
          eth0:
            addresses:
            - ${floating_ip}/32

runcmd:
  - [sgdisk, -e, /dev/sda]
  - [partprobe]
  - [parted, -s, /dev/sda, mkpart, primary, "25%", "100%"]
  - [growpart, /dev/sda, 1]
  - [resize2fs, /dev/sda1]
  - [zpool, create, datapool, /dev/sda2]
  - [zfs, create, datapool/volumes]
  - [zfs, create, datapool/volumes/ext4]
  - [zfs, create, datapool/volumes/block]
  - [apt, update]
  - [apt, upgrade, -y]
  - [systemctl, enable, iscsid]
  - [apt, install, -y, snapd]
  - [snap, install, microk8s, --classic, --channel=1.22/stable]
  - export "PATH=/snap/bin:$PATH"
  - [microk8s, enable, dns]

packages:
  - gdisk
  - zfsutils-linux
