apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: hello-world
  namespace: {{.Release.Namespace}}
spec:
  hosts:
    - {{.Values.host}}
  gateways:
    - hello-world
  http:
    - route:
        - destination:
            host: hello-world
