repositories:
  - name: incubator
    url: https://charts.helm.sh/incubator
  - name: openebs-zfslocalpv
    url: https://openebs.github.io/zfs-localpv

releases:
  - name: operator
    namespace: openebs
    chart: openebs-zfslocalpv/zfs-localpv
    createNamespace: true

  - name: storage-class
    namespace: openebs
    chart: incubator/raw
    needs:
      - operator
    values:
      - resources:
          - apiVersion: storage.k8s.io/v1
            kind: StorageClass
            metadata:
              name: datapool-volumes-ext4
            allowVolumeExpansion: true
            parameters:
              poolname: datapool/volumes/ext4
              fstype: "ext4"
            provisioner: zfs.csi.openebs.io
          - apiVersion: storage.k8s.io/v1
            kind: StorageClass
            metadata:
              name: datapool-volumes-block
            allowVolumeExpansion: true
            parameters:
              poolname: datapool/volumes/block
            provisioner: zfs.csi.openebs.io
