repositories:
  - name: incubator
    url: https://charts.helm.sh/incubator
  - name: openebs-zfslocalpv
    url: https://openebs.github.io/zfs-localpv

releases:
  - name: operator
    namespace: openebs
    chart: openebs-zfslocalpv/zfs-localpv
    createNamespace: true
    values:
      - zfsNode:
          kubeletDir: /var/snap/microk8s/common/var/lib/kubelet/

  - name: storage-class
    namespace: openebs
    chart: incubator/raw
    needs:
      - operator
    values:
      - resources:
          - apiVersion: storage.k8s.io/v1
            kind: StorageClass
            metadata:
              name: datapool
            allowVolumeExpansion: true
            parameters:
              poolname: datapool
            provisioner: zfs.csi.openebs.io
