apiVersion: v1
kind: Secret
metadata:
  name: id-chobert-oauth2
  namespace: {{.Release.Namespace}}
type: Opaque
stringData:
  provider: |
    name: oauth2_generic
    label: "id.chobert.fr"
    app_id: "gitlab.chobert.fr"
    app_secret: {{.Values.oidcAppSecret | quote}}
    args:
      client_options:
        site: "https://id.chobert.fr"
        user_info_url: "/auth/realms/master/protocol/openid-connect/userinfo"
        authorize_url: "/auth/realms/master/protocol/openid-connect/auth"
        token_url: "/auth/realms/master/protocol/openid-connect/token"
      user_response_structure:
        id_path: ["sub"]
