apiVersion: v1
kind: Secret
metadata:
  name: registry-storage-config
  namespace: {{.Release.Namespace}}
type: Opaque
stringData:
  config: |
    s3:
      bucket: gitlab-registry
      regionendpoint: minio.chobert.fr
      accesskey: {{.Values.minio.accesskey}}
      secretkey: {{.Values.minio.secretkey}}
