apiVersion: v1
kind: Secret
metadata:
  name: pgbackrest-backblaze-s3-conf
  namespace: {{.Release.Namespace}}
type: Opaque
stringData:
  s3.conf: |
    [global]
    repo1-s3-key={{.Values.backblaze.keyId}}
    repo1-s3-key-secret={{.Values.backblaze.keySecret}}
