apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: "{{.Release.Name}}-database"
  namespace: {{.Release.Namespace}}
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:centos8-13.4-1
  postgresVersion: 13
  instances:
    - name: instance1
      dataVolumeClaimSpec:
        storageClassName: datapool-volumes-ext4
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:centos8-2.35-0
      configuration:
        - secret:
            name: pgbackrest-backblaze-s3-conf
      global:
        repo1-path: /pgbackrest/gitlab/{{.Release.Name}}-database/repo1
      repos:
        - name: repo1
          s3:
            bucket: chobert-database-backups
            endpoint: s3.us-west-001.backblazeb2.com
            region: us-west-001
