apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{.Release.Name}}
  namespace: {{.Release.Namespace}}
spec:
  hosts:
    - {{.Values.host}}
  gateways:
    - {{.Release.Name}}
  http:
    - route:
        - destination:
            host: {{.Release.Name}}
            port:
              number: 8080
