apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "{{.Release.Name}}-ingress-cert"
  namespace: istio-system
spec:
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  secretName: {{.Values.certificate.secretName}}
  commonName: {{.Values.host}}
  dnsNames:
    - {{.Values.host}}
