repositories:
  - name: postgres-operator
    url: git+https://github.com/barodeur/postgres-operator-examples@helm/install?sparse=0&ref=main

releases:
  - name: postgres-operator
    chart: postgres-operator/pgo
    namespace: postgres-operator
    createNamespace: true
