repositories:
  - name: incubator
    url: https://charts.helm.sh/incubator
  - name: istio
    url: https://istio-release.storage.googleapis.com/charts

releases:
  - name: istio-base
    chart: istio/base
    namespace: istio-system
    createNamespace: true

  - name: istiod
    chart: istio/istiod
    namespace: istio-system
    needs:
      - istio-system/istio-base
    values:
      - pilot:
          autoscaleMin: 2

  - name: istio-ingressgateway
    chart: istio/gateway
    namespace: istio-ingress
    createNamespace: false
    needs:
      - istio-system/istio-base
      - istio-system/istiod
    values:
      - service:
          ports:
            - name: status-port
              port: 15021
              protocol: TCP
              targetPort: 15021
            - name: http2
              port: 80
              protocol: TCP
              targetPort: 80
            - name: https
              port: 443
              protocol: TCP
              targetPort: 443
            - name: ssh
              port: 2222
              protocol: TCP
              targetPort: 2222
