repositories:
  - name: metallb
    url: https://metallb.github.io/metallb

releases:
  - name: metallb
    chart: metallb/metallb
    namespace: metallb-system
    createNamespace: true
    values:
      - configInline:
          address-pools:
            - name: default
              protocol: layer2
              addresses:
                - '{{requiredEnv "LOAD_BALANCER_IP"}}/32'
