apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{.Release.Name}}
  namespace: istio-ingress
spec:
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  secretName: {{.Release.Namespace}}-{{.Release.Name}}-cert
  commonName: {{.Values.host}}
  dnsNames:
    - {{.Values.host}}
