apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: "{{.Release.Name}}-shell"
  namespace: {{.Release.Namespace}}
spec:
  hosts:
    - "*"
  gateways:
    - {{.Release.Name}}
  tcp:
    - match:
        - port: 2222
      route:
        - destination:
            host: gitlab-gitlab-shell.gitlab.svc.cluster.local
            port:
              number: 22
