apiVersion: v1
kind: Secret
metadata:
  name: pgbackrest-s3-conf
  namespace: {{.Release.Namespace}}
type: Opaque
stringData:
  s3.conf: |
    [global]
    repo1-s3-key={{.Values.s3.keyId}}
    repo1-s3-key-secret={{.Values.s3.keySecret}}
