apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: {{.Release.Name}}-2
  namespace: {{.Release.Namespace}}
spec:
  postgresVersion: 14
  users:
    - name: postgres
    - name: keycloak
      databases:
        - keycloak
    - name: grafana
      databases:
        - grafana
    - name: gitlab
      databases:
        - gitlab
    - name: matrix
      databases:
        - matrix
  instances:
    - name: instance-1
      replicas: 2
      dataVolumeClaimSpec:
        storageClassName: datapool-volumes-ext4-retained
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 10Gi
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  postgres-operator.crunchydata.com/cluster: {{.Release.Name}}-2
                  postgres-operator.crunchydata.com/instance-set: instance1
  backups:
    pgbackrest:
      configuration:
        - secret:
            name: pgbackrest-backblaze-s3-conf
      global:
        repo1-path: /pgbackrest/{{.Release.Namespace}}/{{.Release.Name}}/repo1
      manual:
        repoName: repo1
        options:
          - --type=full
      repos:
        - name: repo1
          s3:
            bucket: chobert-database-backups-2
            endpoint: 0a86a9442706a574ee2f85897b8ae44c.r2.cloudflarestorage.com
            region: us-east-1
