apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: {{.Release.Name}}
  namespace: {{.Release.Namespace}}
spec:
  postgresVersion: 14
  users:
    - name: postgres
    - name: keycloak
      databases:
        - keycloak
    - name: grafana
      databases:
        - grafana
    - name: gitlab
      databases:
        - gitlab
    - name: matrix
      databases:
        - matrix
  instances:
    - name: instance1
      replicas: 2
      dataVolumeClaimSpec:
        storageClassName: datapool-volumes-ext4
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 10Gi
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
              matchLabels:
                postgres-operator.crunchydata.com/cluster: {{.Release.Name}}
                postgres-operator.crunchydata.com/instance-set: instance1
  backups:
    pgbackrest:
      configuration:
        - secret:
            name: pgbackrest-s3-conf
      global:
        repo1-path: /pgbackrest/{{.Release.Namespace}}/{{.Release.Name}}/repo1
      manual:
        repoName: repo1
        options:
          - --type=full
      repos:
        - name: repo1
          s3:
            bucket: net-chobert-kube-postgres-backups
            endpoint: https://s3.fr-par.scw.cloud
            region: fr-par
