apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: {{.Release.Name}}
  namespace: {{.Release.Namespace}}
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:centos8-14.0-0
  postgresVersion: 14
  users:
    - name: postgres
    - name: keycloak
      databases:
        - keycloak
    - name: grafana
      databases:
        - grafana
    - name: gitlab
      databases:
        - gitlab
  instances:
    - name: instance1
      dataVolumeClaimSpec:
        storageClassName: datapool-volumes-ext4
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 10Gi
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:centos8-2.35-0
      configuration:
        - secret:
            name: pgbackrest-backblaze-s3-conf
      global:
        repo1-path: /pgbackrest/{{.Release.Namespace}}/{{.Release.Name}}/repo1
      manual:
        repoName: repo1
        options:
          - --type=full
      repos:
        - name: repo1
          s3:
            bucket: chobert-database-backups
            endpoint: s3.us-west-001.backblazeb2.com
            region: us-west-001
