apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: {{.Release.Name}}
  namespace: {{.Release.Namespace}}
spec:
  postgresVersion: 14
  users:
    - name: postgres
    - name: keycloak
      databases:
        - keycloak
    - name: grafana
      databases:
        - grafana
    - name: gitlab
      databases:
        - gitlab
    - name: matrix
      databases:
        - matrix
  instances:
    - name: instance1
      dataVolumeClaimSpec:
        storageClassName: datapool-volumes-ext4
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 10Gi
  backups:
    pgbackrest:
      configuration:
        - secret:
            name: pgbackrest-backblaze-s3-conf
      global:
        repo1-path: /pgbackrest/{{.Release.Namespace}}/{{.Release.Name}}/repo1
      manual:
        repoName: repo1
        options:
          - --type=full
      repos:
        - name: repo1
          s3:
            bucket: chobert-database-backups
            endpoint: r2.cloudflarestorage.com
            region: 0a86a9442706a574ee2f85897b8ae44c
