apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "{{.Release.Namespace}}-{{.Release.Name}}-cert"
  namespace: istio-system
spec:
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  secretName: "{{.Release.Namespace}}-{{.Release.Name}}-cert-secret"
  commonName: {{.Values.host}}
  dnsNames:
    - {{.Values.host}}
