apiVersion: v1
kind: Service
metadata:
  name: "{{.Release.Name}}-svc"
  namespace: {{.Release.Namespace}}
  labels:
    app: synapse
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: web
  selector:
    app: synapse
