apiVersion: v1
kind: Service
metadata:
  name: well-known-federation-svc
  namespace: {{.Release.Namespace}}
  labels:
    app: well-known-federation
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: web
  selector:
    app: well-known-federation
